### PR TITLE
Add support for rendering text

### PR DESCRIPTION
**Pull request by epsi1on**
Hey there.
I did add support for rendering text into the library. Both outline and fill.
Text is very flexible, almost all possible options can be used, like text flow direction, font weight and many other stuff.
Have a look at example section.

edit: The `FormattedText` in WPF converts the string into polygon and poly beziers, `WritableBitmapEx` also support filling polygon and beziers, so i've used `FormattedText` to convert text into polygons, then use `WritableBitmapEx.FillPolygon` to fill the polygons.

### CODE REVIEW

**Comment by epsi1on** [comment]
Here is example of rendered text, works as expected
wb

**Comment by rbri** [comment]
As far a i remember the project https://github.com/FormatD/FastWpfGrid has also done some work on supporting text.
You can start with WriteableBitmapEx/LetterGlyphTool.cs if you like to have a look.
From my memories they did some caching work to make this really fast.

**Comment by epsi1on** [comment]
Glyph technique is a good one, and i think i have seen it, but the glyph solution is not a general solution I think.
There are some languages like Arabic and Persian characters, which glyph technique must be used with some considerations, at least it is not a ready made solution. 
This pull request, uses `FormattedText`, which a low level and flexible type and is a general purpose method I think:

Provides low-level control for drawing text in Windows Presentation Foundation (WPF) applications. ([MSDN](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.formattedtext?view=windowsdesktop-7.0))

With no doubt, the speed of Glyph technique can be very high, at least higher than FillText which in this pull request.
The `FormattedText` converts the string into polygon and poly beziers, `WritableBitmapEx` also support filling polygon and beziers, so i've used `FormattedText` to convert text into polygons, then use `WritableBitmapEx` to fill the polygons.

**Comment by epsi1on** [comment]
I think (and hope) the compatibility is considered within the code. The code only uses `FormattedText` which is a WPF builtin class, and that class will convert text into polygons and polybeziers I think. Then the library fills those geometries.

**Comment by reneschulte** [comment]
Thank you for your contribution.

**Comment by parsile** [comment]
Hi, when do you plan to publish a new version of nuget package containing the text rendering support? :)

**Comment by martinransbachbender** [comment]
@reneschulte 

> Hi, when do you plan to publish a new version of nuget package containing the text rendering support? :)

As far as I know this has still not been published, I would appreciate :)

**Comment by reneschulte** [comment]
I do not even have the tools installed anymore to build a Nuget package. Please use the source code directly.

**Pull request merged**
