### PR TITLE
crop fixed for images without an alpha channel

### PR DESCRIPTION
**Pull request by fdugdale112**

### CODE REVIEW

**Comment by reneschulte** [comment]
Thanks for the PR. I'm a bit hesitant to merge it in as WBX is aiming at ARGB format and there's a ConvertToPbgra32Format method to convert to ARGB. 
We can't use the WB ctor from WPF which takes the format as it would break x-plat for platforms where there's only ARGB and this WB ctor is non-existent. 
At least this should be put in a #if WPF precompiler directive.

**Comment by fdugdale112** [comment]
how about I check the number of channels and if there isn't an alpha, call the ConvertToPbgra32Format method from within the crop function. only hesitation is we'd be returning an image in a different format to what we received.

either that or do the check and throw an error explaining that only ARGB images are supported.

keen to know your thoughts

**Comment by reneschulte** [comment]
> either that or do the check and throw an error explaining that only ARGB images are supported.
> 
> keen to know your thoughts

I think this is the way to go. Explicit throw an error with a hint which function to call first, is better than implicit and doing the conversion automatically but hidden. 
IIRC there might be similar code somewhere in WBX that check for that.

**Comment by reneschulte** [comment]
Thanks for your contribution. 🙏

**Pull request merged**
